spring.application.name=restaurant

spring.config.import=classpath:/secrets.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/tomato
spring.datasource.username=${db.username}
spring.datasource.password= ${db.password}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql =true 

spring.jpa.hibernate.ddl-auto=create


auth.token.expirationInMills=3600000

auth.token.jwtSecret=0bf329b7e99e95e0e1b3a4aa92c5fc5f234ddf4a3f5ca96cebd344fe3acf3fff4894d7b7
